package org.isaqb.onlineexam;

import javax.annotation.Generated;

@Generated("generated by Gradle Buildfile")
public class BuildInfo {
	
	private static String VERSION = "0.3";
	private static String BUILD_TIMESTAMP = "2022.02.22 16:36";
	
	public static String getVersion() {
        return VERSION;
    }
	
	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
}
