== isaqb-mock-exam-ui

// [![Gradle Build](https://github.com/janmaterne/isaqb-mock-exam-ui/actions/workflows/gradle-build.yml/badge.svg)](https://github.com/janmaterne/isaqb-mock-exam-ui/actions/workflows/gradle-build.yml)

=== English

Interactive UI for processing the mock foundation exam of the ISAQB

==== Using it

The application requires internet access on startup, because the application loads all tasks directly from the repository on Github.

#TODO: Upload distro to ... where? GitHub?#

After extracting the distribution archive you'll find a start script `run.bat` (Windows) or `run.sh` (Linux, MacOS) in the root directory.
With this script you could start the application which will open port `8080` for incoming requests from the browser.
So opening http://localhost:8080/ should work.


==== Developing it

// ** a "developing" section, for motivated devs who want to contribute and enhance it



=== German

Interaktives UI für das Üben der Mockprüfung des iSAQB Foundation Level.

==== Nutzung

Die Anwendung benötigt Internetzugang zum Startzeitpunkt, da die Anwendung dann alle Fragen direkt aus dem Repository bei Github herunterlädt.

Nachdem die Distribution heruntergeladen wurde, kann man ein Startskript `run.bat` (Windows) bzw. `run.sh` (Linux, MacOS) im Wurzelverzeichnis finden.
Über dieses Skript kann die Anwendung gestartet werden, welche den Port `8080` öffnet, um Anfragen eines Browsers zu beantworten.
Ein Öffnen von http://localhost:8080/ sollte daher reichen.


==== Weiterentwicklung



