== isaqb-mock-exam-ui

// [![Gradle Build](https://github.com/janmaterne/isaqb-mock-exam-ui/actions/workflows/gradle-build.yml/badge.svg)](https://github.com/janmaterne/isaqb-mock-exam-ui/actions/workflows/gradle-build.yml)

=== English

Interactive UI for processing the mock foundation exam of the ISAQB

==== Using it

The application requires internet access on startup, because the application loads all tasks directly from the repository on Github.

There are three types of distributions:

* as startable JAR file
* as Docker image
* as distribution with embedded Java runtime

The docker image is available on https://hub.docker.com/r/janmaterne/onlinetrainer[DockerHub] while the others are released on https://github.com/janmaterne/isaqb-mock-exam-ui/releases[GitHub].

There is (hopefully ;) a running instance at https://isaqb-onlinetrainer.herokuapp.com/

===== Startable JAR

If you have a Java runtime installed (required Java16+), you could download the JAR and start it as any startable JAR:
`java -Dfile.encoding=UTF-8 --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -jar onlinetrainer-{VERSION}.jar`
Here you have to specify the file encoding, as the application produces UTF-8 characters.
Additionally you should "open" the Java module system.

===== Docker image

You could start the application by starting the docker image:
`docker run -p 8080:8080 janmaterne/onlinetrainer:latest`
Here you have to publish port - maybe with changing it `-p 80:8080`.
After starting the container you could access the application via the specified port on http://localhost:8080.

===== Distribution

After extracting the distribution archive you'll find a start script `run.bat` (Windows) or `run.sh` (Linux, MacOS) in the root directory.
With this script you could start the application which will open port `8080` for incoming requests from the browser.
So opening http://localhost:8080/ should work.

==== Developing it

// ** a "developing" section, for motivated devs who want to contribute and enhance it



=== German

Interaktives UI für das Üben der Mockprüfung des iSAQB Foundation Level.

==== Nutzung

Die Anwendung benötigt Internetzugang zum Startzeitpunkt, da die Anwendung dann alle Fragen direkt aus dem Repository bei Github herunterlädt.

Es gibt drei Arten der Distribution

* als startbares JAR
* als Docker Image
* als Distribution mit mitgebrachter Java Laufzeit

Das Docker Image kann von https://hub.docker.com/r/janmaterne/onlinetrainer[DockerHub] bezogen werden während die anderen Artefakte als Releases auf https://github.com/janmaterne/isaqb-mock-exam-ui/releases[GitHub] erhätlich sind.

Eine laufende Instanz ist (hoffentlich ;) unter https://isaqb-onlinetrainer.herokuapp.com/

===== Starbares JAR

Wenn eine Java Laufzeit installiert ist (es wird mindestens ein Java 16 benötigt), kann einfach das JAR heruntergeladen und wie gewohnt gestartet werden:
`java -Dfile.encoding=UTF-8 --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -jar mockexam-{VERSION}.jar`
Dabei muss das Encoding gesetzt werden, da die Anwendung UTF-8 Zeichen erzeugt.
Auch sollte das Java Modulsystem befriedigt werden.

===== Docker Image

Man kann die Anwendung durch per Docker Image starten:
`docker run -p 8080:8080 janmaterne/onlinetrainer:latest`
Hier muss der Port veröffentlicht werden - eventuell mit Änderung desselben: `-p 80:8080`.
Nach dem Start des Containers kann die Anwendung über den spezifizierten Port erreicht werden: http://localhost:8080.

===== Distribution   

Nachdem die Distribution heruntergeladen wurde, kann man ein Startskript `run.bat` (Windows) bzw. `run.sh` (Linux, MacOS) im Wurzelverzeichnis finden.
Über dieses Skript kann die Anwendung gestartet werden, welche den Port `8080` öffnet, um Anfragen eines Browsers zu beantworten.
Ein Öffnen von http://localhost:8080/ sollte daher reichen.


==== Weiterentwicklung



