package org.isaqb.onlinetrainer;

import java.util.Map;

import jakarta.annotation.Generated;

@Generated("generated by Maven Buildfile")
public class BuildInfo {

	private static final String VERSION = "0.9-SNAPSHOT";
	private static final String BUILD_TIMESTAMP = "2024.01.30 14:04";
	private static final String GIT_COMMIT_SHORTHASH = "9756294";
	private static final String GIT_COMMIT_MESSAGE = """
		update dependencies
	""";
	private static final String GIT_COMMIT_TSTAMP = "2024-01-20T11:19:02+0100";

	public static String getVersion() {
        return VERSION;
    }

	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
	public static String getGitCommitShortHash() {
		return GIT_COMMIT_SHORTHASH;
	}
	
	public static String getGitCommitMessage() {
		return GIT_COMMIT_MESSAGE;
	}
	
	public static String getGitCommitTstamp() {
		return GIT_COMMIT_TSTAMP;
	}
	
	public static Map<String, Object> get() {
		return Map.of(
			"app.version", getVersion(),
			"app.buildtime", getBuildTimestamp(),
			"app.git.commit.shorthash", getGitCommitShortHash(),
			"app.git.commit.message", getGitCommitMessage(),
			"app.git.commit.tstamp", getGitCommitTstamp()
		);
	}

}
