package org.isaqb.onlinetrainer;

import javax.annotation.Generated;

@Generated("generated by Gradle Buildfile")
public class BuildInfo {
	
	private static String VERSION = "__VERSION";
	private static String BUILD_TIMESTAMP = "__BUILD_TIMESTAMP";
	
	public static String getVersion() {
        return VERSION;
    }
	
	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
}
