package org.isaqb.onlinetrainer;

import javax.annotation.Generated;

@Generated("generated by Gradle Buildfile")
public class BuildInfo {
	
	private static final String VERSION = "__VERSION";
	private static final String BUILD_TIMESTAMP = "__BUILD_TIMESTAMP";
	private static final String GIT_COMMIT_SHORTHASH = "__GIT_COMMIT_HASH";
	private static final String GIT_COMMIT_MESSAGE = "__GIT_COMMIT_MESSAGE";
	private static final String GIT_COMMIT_TSTAMP = "__GIT_COMMIT_TSTAMP";
	
	public static String getVersion() {
        return VERSION;
    }
	
	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
	public static String getGitCommitShortHash() {
		return GIT_COMMIT_SHORTHASH;
	}
	
	public static String getGitCommitMessage() {
		return GIT_COMMIT_MESSAGE;
	}
	
	public static String getGitCommitTstamp() {
		return GIT_COMMIT_TSTAMP;
	}
	
}
