package org.isaqb.onlinetrainer;

import java.util.Map;

import jakarta.annotation.Generated;

@Generated("generated by Maven Buildfile")
public class BuildInfo {

	private static final String VERSION = "@project.version@";
	private static final String BUILD_TIMESTAMP = "@timestamp@";
	private static final String GIT_COMMIT_SHORTHASH = "@git.commit.id.abbrev@";
	private static final String GIT_COMMIT_MESSAGE = """
		@git.commit.message.full@
	""";
	private static final String GIT_COMMIT_TSTAMP = "@git.commit.time@";

	public static String getVersion() {
        return VERSION;
    }

	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
	public static String getGitCommitShortHash() {
		return GIT_COMMIT_SHORTHASH;
	}
	
	public static String getGitCommitMessage() {
		return GIT_COMMIT_MESSAGE;
	}
	
	public static String getGitCommitTstamp() {
		return GIT_COMMIT_TSTAMP;
	}
	
	public static Map<String, Object> get() {
		return Map.of(
			"app.version", getVersion(),
			"app.buildtime", getBuildTimestamp(),
			"app.git.commit.shorthash", getGitCommitShortHash(),
			"app.git.commit.message", getGitCommitMessage(),
			"app.git.commit.tstamp", getGitCommitTstamp()
		);
	}

}
