# Where is the source of the introduction document?
introduction: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/preamble/introduction.adoc


# Inject a JS-Snippet for Autoreload of the page. (Works only if DevTools are available.)
inject-autoload-js: false

# Configure the quizmode.
quizmode:
    max-numbers-of-questions: 5


#TODO At the moment only the fixed 'foundation' is supported.
# Define the source for the tasks and group them by topic.
tasks:
    # Start a new topic with key 'ddd'
    ddd:
        # International name for displaying.
        name:
            DE: Domain Driven Design
            EN: Domain Driven Design
        # Where to find the original AsciiDoc code with the tasks content?
        # A task in this context contains the question, data and possible answers - all are provided in the "question"-docs.
        urls:
        - url-template: https://raw.githubusercontent.com/janmaterne/isaqb-quiz-questions/master/src/questions/ddd/1-basics/question-{NR}.adoc
          from: 1
          to: 5
          # URLs to load generated from a template replacing the placeholder {NR}
          # with a 2-digit value between 'from' and 'to' (inclusive).
          # URLs which cant be loaded are ignored.
          # Topics without any URLs are also ignored.
    foundation-part1:
        name:
            DE: Foundation Teil 1
            EN: Foundation Part 1
        urls:
        - url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
          from: 1
          to: 10
    foundation-part2:
        name:
            DE: Foundation Teil 2
            EN: Foundation Part 2
        urls:
        - url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
          from: 11
          to: 20
    foundation-part3:
        name:
            DE: Foundation Teil 3
            EN: Foundation Part 3
        urls:
        - url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
          from: 21
          to: 30
    foundation-part4:
        name:
            DE: Foundation Teil 4
            EN: Foundation Part 4
        urls:
        - url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
          from: 31
          to: 39
    foundation:
        name:
            DE: Foundation
            EN: Foundation
        # You also could reference topics.
        refs:
        - foundation-part1
        - foundation-part2
        - foundation-part3
        - foundation-part4



# Topics can be grouped to exams.
# An exam has additional requirements for passing:
# - a minimum of points to achieve
# - a maximum amount of time
exams:
    mock:
        name:
            DE: Foundation Level Mock Prüfung
            EN: Foundation Level Mock Exam
        required-points: 30
        max-time-in-minutes: 60
        task-refs:
        - foundation
        #urls:
        #- url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
        #  from: 4
        #  to: 4
    found-test-1:
        name:
            DE: Foundation Part 1
            EN: Foundation Part 1
        required-points: 30
        max-time-in-minutes: 60
        task-refs:
        - foundation-part1
    found-test-2:
        name:
            DE: Foundation Part 2
            EN: Foundation Part 2
        required-points: 30
        max-time-in-minutes: 60
        task-refs:
        - foundation-part2
    found-test-3:
        name:
            DE: Foundation Part 3
            EN: Foundation Part 3
        required-points: 30
        max-time-in-minutes: 60
        task-refs:
        - foundation-part3
    found-test-4:
        name:
            DE: Foundation Part 4
            EN: Foundation Part 4
        required-points: 30
        max-time-in-minutes: 60
        task-refs:
        - foundation-part4





cache:
    # How long should an entry live in the ADOC-Cache?
    ttl-hours: 72


# Increase Header-Size to store UIData as cookie
server:
    max-http-header-size: 250KB

# https://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/common-application-properties.html
spring:
    # Encoding for handling Umlauts
    http:
        encoding:
            charset: UTF-8
            enabled: true
    thymeleaf:
        encoding: UTF-8
    # JPA for Caching the remote access (loading the adoc sources)
    datasource:
        url: jdbc:h2:~/mock-cache # jdbc:h2:mem:mock-cache
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        # on 'true' see http://localhost:8080/h2-console
        console.enabled: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false

# Specify Logging
logging:
    level:
        org.isaqb.onlineexam: INFO
        org.isaqb.onlineexam.DataConfiguration: TRACE
    pattern:
        consolXe: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n"
        console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}:%L){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
