mock:
    # Where is the source of the introduction document?
    introduction: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/preamble/introduction.adoc
    # Where to find the original AsciiDoc code with the tasks content?
    # A task in this context contains the question, data and possible answers - all are provided in the "question"-docs.
    url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
    from: 1
    to: 5
    #to: 39
    # How many points are required to pass the exam?
    requiredPoints: 30


quizmode:
    max-numbers-of-questions: 5

# Define possible (additional) questions for the quiz mode.
# quiz - topic - config
quiz:
    ddd:
        name:
            DE: Domain Driven Design
            EN: Domain Driven Design
        urls:
        - url-template: xx 
          from: 1
          to: 2
        - url-template: yy
          from: 1
          to: 2
    base:
        name:
            DE: Basis
            EN: Foundation Basis
        urls:
        - url-template: https://raw.githubusercontent.com/isaqb-org/examination-foundation/main/raw/mock_exam/docs/questions/question-{NR}.adoc
          from: 33
          to: 35    
    foundation-chapter1:
        name:
            DE: Foundation Kapitel 1
            EN: Foundation Chapter 1
        urls:
        - url-template: url
          from: 1
          to: 2
    foundation-chapter2:
        name:
            DE: Foundation Kapitel 2
            EN: Foundation Chapter 2
        urls:
        - url-template: url
          from: 1
          to: 2
    foundation:
        name:
            DE: Foundation
            EN: Foundation
        refs:
        - foundation-chapter1
        - foundation-chapter2



# Increase Header-Size to store UIData as cookie
server:
    max-http-header-size: 250KB

# https://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/common-application-properties.html
spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
    thymeleaf:
        encoding: UTF-8