package org.isaqb.onlineexam.mockexam;

import javax.annotation.Generated;

@Generated("generated by Gradle Buildfile")
public class BuildInfo {
	
	private static String VERSION = "0.0.1-SNAPSHOT";
	private static String BUILD_TIMESTAMP = "2021.11.01 19:48";
	
	public static String getVersion() {
        return VERSION;
    }
	
	public static String getBuildTimestamp() {
		return BUILD_TIMESTAMP;
	}
	
}
